# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "object_number",
                    models.CharField(
                        help_text="Ziffernfolge wie erfasst, z. B. 623 oder 82",
                        max_length=8,
                    ),
                ),
                (
                    "object_number_numeric",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            "object_number", output_field=models.PositiveIntegerField()
                        ),
                        output_field=models.PositiveIntegerField(),
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("street", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "management_type",
                    models.CharField(
                        choices=[
                            ("weg", "WEG"),
                            ("rental", "Mietverwaltung"),
                            ("weg_with_se", "WEG mit Sondereigentumsverwaltung"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "neu"),
                            ("takeover", "in Übernahme"),
                            ("active", "aktiv"),
                            ("archived", "archiviert"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("takeover_from", models.DateField(blank=True, null=True)),
                ("takeover_to", models.DateField(blank=True, null=True)),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "previous_manager_name",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "previous_manager_street",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "previous_manager_house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "previous_manager_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "previous_manager_city",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "previous_manager_contact_person",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "previous_manager_reference",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "expected_unit_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("sepa_used", models.BooleanField(blank=True, null=True)),
                (
                    "special_levies_in_period",
                    models.BooleanField(blank=True, null=True),
                ),
                ("is_test", models.BooleanField(default=False)),
                (
                    "drive_root_folder_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "drive_root_folder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("drive_root_verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "active_key",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                deleted_at__isnull=True,
                                then=django.db.models.functions.comparison.Cast(
                                    "object_number",
                                    output_field=models.PositiveIntegerField(),
                                ),
                            ),
                            default=models.Value(None),
                        ),
                        output_field=models.PositiveIntegerField(null=True),
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "objects",
                "ordering": ["object_number_numeric"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit_number", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Wohnung"),
                            ("commercial", "Gewerbe"),
                            ("parking", "Stellplatz"),
                            ("garage", "Garage"),
                            ("underground_parking", "Tiefgarage"),
                            ("cellar", "Keller"),
                            ("other", "Sonstige"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("unit_label", models.CharField(max_length=80)),
                ("unit_label_normalized", models.CharField(max_length=80)),
                (
                    "co_ownership_share",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "co_ownership_share_base",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("building", models.CharField(blank=True, max_length=80, null=True)),
                ("location", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "house_fee_monthly",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("status", models.CharField(default="active", max_length=16)),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "bestätigt"),
                            ("ai_suggested", "KI-Vorschlag"),
                            ("incomplete", "unvollständig"),
                        ],
                        default="incomplete",
                        max_length=16,
                    ),
                ),
                (
                    "se_managed",
                    models.BooleanField(
                        blank=True,
                        help_text="Sondereigentumsverwaltung durch uns",
                        null=True,
                    ),
                ),
                ("vacancy_confirmed", models.BooleanField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "active_key",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                deleted_at__isnull=True,
                                then=models.F("unit_label_normalized"),
                            ),
                            default=models.Value(None),
                        ),
                        output_field=models.CharField(max_length=80, null=True),
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="objects.managedobject",
                    ),
                ),
            ],
            options={
                "db_table": "units",
                "ordering": ["object_id", "unit_label_normalized"],
            },
        ),
        migrations.AddIndex(
            model_name="managedobject",
            index=models.Index(fields=["status"], name="ix_objects_status"),
        ),
        migrations.AddIndex(
            model_name="managedobject",
            index=models.Index(fields=["drive_root_folder_id"], name="ix_objects_drive_root"),
        ),
        migrations.AddConstraint(
            model_name="managedobject",
            constraint=models.UniqueConstraint(fields=("active_key",), name="uq_objects_number_active"),
        ),
        migrations.AddConstraint(
            model_name="managedobject",
            constraint=models.CheckConstraint(
                condition=models.Q(("object_number__regex", "^[0-9]+$")),
                name="ck_objects_number_digits",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedobject",
            constraint=models.CheckConstraint(
                condition=models.Q(("management_type__in", ["weg", "rental", "weg_with_se"])),
                name="ck_objects_mgmt",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedobject",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["new", "takeover", "active", "archived"])),
                name="ck_objects_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedobject",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("takeover_to__isnull", True),
                    ("takeover_from__isnull", True),
                    ("takeover_from__lte", models.F("takeover_to")),
                    _connector="OR",
                ),
                name="ck_objects_takeover",
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["object", "unit_number"], name="ix_units_object_number"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["external_ref"], name="ix_units_external_ref"),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("object", "active_key"), name="uq_units_object_label_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "unit_type__in",
                        [
                            "apartment",
                            "commercial",
                            "parking",
                            "garage",
                            "underground_parking",
                            "cellar",
                            "other",
                        ],
                    )
                ),
                name="ck_units_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "inactive"])),
                name="ck_units_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_status__in", ["confirmed", "ai_suggested", "incomplete"])),
                name="ck_units_data_status",
            ),
        ),
    ]
