# Generated by Django 5.2.17 on 2026-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedobject",
            name="is_system_inbox",
            field=models.BooleanField(
                default=False,
                help_text="technisches Eingangsobjekt für nicht zugeordnete Dokumente (Synchronisation)",
            ),
        ),
    ]
