# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveSyncAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq_no", models.PositiveIntegerField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("inventory", "Inventur"),
                            ("find_root", "Objektordner suchen"),
                            ("register_folder", "Ordner registrieren"),
                            ("create_folder", "Ordner anlegen"),
                            ("rename_folder", "Ordner umbenennen"),
                            ("move_file", "Datei verschieben"),
                            ("create_review", "Review-Fall anlegen"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_drive_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "parent_drive_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "name_before",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name_after", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file_count_before",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "file_count_after",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "id_hash_before",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 der sortierten Datei-IDs vor der Umbenennung",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "id_hash_after",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("planned", models.BooleanField(default=True)),
                ("executed", models.BooleanField(default=False)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.CharField(blank=True, max_length=16, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "drive_sync_actions",
            },
        ),
        migrations.CreateModel(
            name="DriveSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "läuft"),
                            ("done", "fertig"),
                            ("failed", "fehlgeschlagen"),
                            ("aborted", "abgebrochen"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "root_matches",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "file_count_before",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "file_count_after",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("actions_planned", models.PositiveIntegerField(default=0)),
                ("actions_executed", models.PositiveIntegerField(default=0)),
                ("no_changes", models.BooleanField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "drive_sync_runs",
            },
        ),
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="google", max_length=24)),
                ("account_email", models.CharField(max_length=254)),
                ("scopes", models.CharField(max_length=500)),
                ("storage_mode", models.CharField(default="db", max_length=16)),
                ("access_token_encrypted", models.BinaryField(blank=True, null=True)),
                ("refresh_token_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "key_version",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("access_expires_at", models.DateTimeField(blank=True, null=True)),
                ("refresh_obtained_at", models.DateTimeField(blank=True, null=True)),
                ("last_refresh_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_refresh_status",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "last_refresh_error",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                ("status", models.CharField(default="active", max_length=16)),
            ],
            options={
                "db_table": "oauth_tokens",
            },
        ),
        migrations.CreateModel(
            name="DriveNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node_kind",
                    models.CharField(
                        choices=[
                            ("data_root", "Wurzel 01_Daten"),
                            ("object_root", "Objektordner"),
                            ("main_folder", "Hauptordner 01 bis 06"),
                            ("subfolder", "Unterordner"),
                            ("owner_file_folder", "Eigentümerakte"),
                            ("owner_file_subfolder", "Unterordner der Eigentümerakte"),
                            ("tenant_file_folder", "Mieterakte"),
                            ("tenant_file_subfolder", "Unterordner der Mieterakte"),
                            ("list_file", "Listen-Datei"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("owner_list", "Eigentümerliste"),
                            ("tenant_list", "Mieterliste"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "list_format",
                    models.CharField(
                        blank=True,
                        choices=[("xlsx", "Excel"), ("pdf", "PDF")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=128, unique=True)),
                (
                    "drive_parent_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("drive_name", models.CharField(max_length=255)),
                (
                    "expected_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mime_type", models.CharField(blank=True, max_length=120, null=True)),
                ("is_folder", models.BooleanField(default=True)),
                ("created_by_app", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "aktiv"),
                            ("missing", "in Drive nicht gefunden"),
                            ("trashed", "im Papierkorb"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="category_code",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentcategory",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        blank=True,
                        db_column="object_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drive_nodes",
                        to="objects.managedobject",
                    ),
                ),
            ],
            options={
                "db_table": "drive_nodes",
            },
        ),
    ]
