# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models

import objektakte.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0003_fremdschluessel_parties_review"),
        ("drive", "0001_initial"),
        ("objects", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="drivenode",
            name="owner_file",
            field=models.ForeignKey(
                blank=True,
                db_column="owner_file_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drive_nodes",
                to="parties.ownerfile",
            ),
        ),
        migrations.AddField(
            model_name="drivenode",
            name="parent_node",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_node_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="drive.drivenode",
            ),
        ),
        migrations.AddField(
            model_name="drivenode",
            name="subfolder",
            field=models.ForeignKey(
                blank=True,
                db_column="subfolder_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="documents.documentsubfolder",
            ),
        ),
        migrations.AddField(
            model_name="drivenode",
            name="tenant_file",
            field=models.ForeignKey(
                blank=True,
                db_column="tenant_file_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drive_nodes",
                to="parties.tenantfile",
            ),
        ),
        migrations.AddField(
            model_name="drivesyncaction",
            name="drive_node",
            field=models.ForeignKey(
                blank=True,
                db_column="drive_node_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="drive.drivenode",
            ),
        ),
        migrations.AddField(
            model_name="drivesyncrun",
            name="object",
            field=models.ForeignKey(
                blank=True,
                db_column="object_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sync_runs",
                to="objects.managedobject",
            ),
        ),
        migrations.AddField(
            model_name="drivesyncrun",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                db_column="triggered_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="drivesyncaction",
            name="sync_run",
            field=models.ForeignKey(
                db_column="sync_run_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions",
                to="drive.drivesyncrun",
            ),
        ),
        migrations.AddField(
            model_name="oauthtoken",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="drivenode",
            index=models.Index(fields=["object", "node_kind"], name="ix_drive_nodes_object_kind"),
        ),
        migrations.AddConstraint(
            model_name="drivenode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "node_kind__in",
                        [
                            "data_root",
                            "object_root",
                            "main_folder",
                            "subfolder",
                            "owner_file_folder",
                            "owner_file_subfolder",
                            "tenant_file_folder",
                            "tenant_file_subfolder",
                            "list_file",
                        ],
                    )
                ),
                name="ck_drive_nodes_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="drivenode",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "missing", "trashed"])),
                name="ck_drive_nodes_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="drivenode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("node_kind", "list_file"), _negated=True),
                        ("list_type__isnull", True),
                        ("list_format__isnull", True),
                    ),
                    models.Q(
                        ("node_kind", "list_file"),
                        ("list_type__in", ["owner_list", "tenant_list"]),
                        ("list_format__in", ["xlsx", "pdf"]),
                    ),
                    _connector="OR",
                ),
                name="ck_drive_nodes_list",
            ),
        ),
        migrations.AddIndex(
            model_name="drivesyncrun",
            index=models.Index(fields=["object", "started_at"], name="ix_sync_runs_object"),
        ),
        migrations.AddConstraint(
            model_name="drivesyncrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["running", "done", "failed", "aborted"])),
                name="ck_sync_runs_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="drivesyncaction",
            constraint=models.UniqueConstraint(fields=("sync_run", "seq_no"), name="uq_sync_actions_seq"),
        ),
        migrations.AddConstraint(
            model_name="drivesyncaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action_type__in",
                        [
                            "inventory",
                            "find_root",
                            "register_folder",
                            "create_folder",
                            "rename_folder",
                            "move_file",
                            "create_review",
                        ],
                    )
                ),
                name="ck_sync_actions_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="drivesyncaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("result__isnull", True),
                    ("result__in", ["ok", "skipped", "failed"]),
                    _connector="OR",
                ),
                name="ck_sync_actions_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthtoken",
            constraint=models.UniqueConstraint(
                fields=("provider", "account_email"), name="uq_oauth_provider_account"
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthtoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("storage_mode__in", ["db", "docker_secret"])),
                name="ck_oauth_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthtoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "expired", "revoked"])),
                name="ck_oauth_status",
            ),
        ),
        migrations.AddField(
            model_name="drivenode",
            name="position_key",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        status="active",
                        then=objektakte.db.ConcatWS(
                            models.Value("|"),
                            models.F("node_kind"),
                            django.db.models.functions.comparison.Coalesce(
                                models.F("object_id"),
                                models.Value(0),
                                output_field=models.IntegerField(),
                            ),
                            django.db.models.functions.comparison.Coalesce(
                                models.F("category_id"),
                                models.Value(""),
                                output_field=models.CharField(),
                            ),
                            django.db.models.functions.comparison.Coalesce(
                                models.F("subfolder_id"),
                                models.Value(0),
                                output_field=models.IntegerField(),
                            ),
                            django.db.models.functions.comparison.Coalesce(
                                models.F("owner_file_id"),
                                models.Value(0),
                                output_field=models.IntegerField(),
                            ),
                            django.db.models.functions.comparison.Coalesce(
                                models.F("tenant_file_id"),
                                models.Value(0),
                                output_field=models.IntegerField(),
                            ),
                            django.db.models.functions.comparison.Coalesce(
                                models.F("list_type"),
                                models.Value(""),
                                output_field=models.CharField(),
                            ),
                            django.db.models.functions.comparison.Coalesce(
                                models.F("list_format"),
                                models.Value(""),
                                output_field=models.CharField(),
                            ),
                        ),
                    ),
                    default=models.Value(None),
                ),
                output_field=models.CharField(max_length=190, null=True),
            ),
        ),
        migrations.AddConstraint(
            model_name="drivenode",
            constraint=models.UniqueConstraint(fields=("position_key",), name="uq_drive_nodes_position"),
        ),
    ]
