# Generated by Django 5.2.17 on 2026-09-11 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0002_fremdschluessel_parties_documents"),
        ("objects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TakeoverSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("drive_folder_id", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "detected_object_number",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "neu"),
                            ("linked", "Objekt zugeordnet"),
                            ("done", "übernommen"),
                            ("failed", "fehlgeschlagen"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("files_registered", models.PositiveIntegerField(default=0)),
                ("files_skipped", models.PositiveIntegerField(default=0)),
                ("last_run_id", models.PositiveIntegerField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        blank=True,
                        db_column="object_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="takeover_sources",
                        to="objects.managedobject",
                    ),
                ),
            ],
            options={
                "db_table": "takeover_sources",
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["new", "linked", "done", "failed"])
                        ),
                        name="ck_takeover_sources_status",
                    )
                ],
            },
        ),
    ]
