# Generated by Django 5.2.17 on 2026-09-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "Nutzer"),
                            ("system", "System"),
                            ("worker", "Worker"),
                        ],
                        max_length=16,
                    ),
                ),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("user_email", models.CharField(blank=True, max_length=254, null=True)),
                ("action", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=48)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("object_id", models.BigIntegerField(blank=True, null=True)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=500, null=True)),
                ("request_id", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "ip_address",
                    models.BinaryField(blank=True, max_length=16, null=True),
                ),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "audit_events",
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "occurred_at"],
                        name="ix_audit_entity",
                    ),
                    models.Index(fields=["user_id", "occurred_at"], name="ix_audit_user"),
                    models.Index(fields=["object_id", "occurred_at"], name="ix_audit_object"),
                    models.Index(fields=["action", "occurred_at"], name="ix_audit_action"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("actor_type__in", ["user", "system", "worker"])),
                        name="ck_audit_actor",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IbanAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessed_at", models.DateTimeField()),
                ("actor_type", models.CharField(max_length=16)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("user_email", models.CharField(blank=True, max_length=254, null=True)),
                ("entity_type", models.CharField(max_length=16)),
                ("entity_id", models.BigIntegerField()),
                ("purpose", models.CharField(max_length=24)),
                ("request_id", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "ip_address",
                    models.BinaryField(blank=True, max_length=16, null=True),
                ),
            ],
            options={
                "db_table": "iban_access_log",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "accessed_at"],
                        name="ix_iban_log_entity",
                    ),
                    models.Index(fields=["user_id", "accessed_at"], name="ix_iban_log_user"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("actor_type__in", ["user", "system"])),
                        name="ck_iban_log_actor",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("entity_type__in", ["owner", "tenant"])),
                        name="ck_iban_log_entity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("purpose__in", ["edit", "export", "rekey"])),
                        name="ck_iban_log_purpose",
                    ),
                ],
            },
        ),
    ]
