# Generated by Django 5.2.17 on 2026-09-10 14:27

from decimal import Decimal

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models

import objektakte.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0002_fremdschluessel_ai_drive_objects"),
        ("imports", "0001_initial"),
        ("objects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lease_reference",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "base_rent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "utilities_prepayment",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "heating_prepayment",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "total_rent",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(base_rent__isnull=True, then=models.Value(None)),
                            default=django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("base_rent"),
                                    "+",
                                    django.db.models.functions.comparison.Coalesce(
                                        models.F("utilities_prepayment"),
                                        models.Value(
                                            Decimal("0"),
                                            output_field=models.DecimalField(decimal_places=2, max_digits=12),
                                        ),
                                    ),
                                ),
                                "+",
                                django.db.models.functions.comparison.Coalesce(
                                    models.F("heating_prepayment"),
                                    models.Value(
                                        Decimal("0"),
                                        output_field=models.DecimalField(decimal_places=2, max_digits=12),
                                    ),
                                ),
                            ),
                        ),
                        output_field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "deposit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash_account", "Kautionskonto"),
                            ("savings_book", "Sparbuch"),
                            ("bank_guarantee", "Bankbürgschaft"),
                            ("pledge", "Verpfändung"),
                            ("insurance", "Kautionsversicherung"),
                            ("other", "sonstige"),
                            ("unknown", "unbekannt"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "deposit_notes",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rent_adjustment_type",
                    models.CharField(
                        choices=[
                            ("none", "keine"),
                            ("graduated", "Staffel"),
                            ("indexed", "Index"),
                            ("unknown", "unbekannt"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "persons_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "bestätigt"),
                            ("ai_suggested", "KI-Vorschlag"),
                            ("incomplete", "unvollständig"),
                        ],
                        default="incomplete",
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leases",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "source_import_row",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_import_row_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="imports.importrow",
                    ),
                ),
            ],
            options={
                "db_table": "leases",
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("natural_person", "natürliche Person"),
                            ("legal_entity", "juristische Person"),
                            ("community", "Gemeinschaft"),
                        ],
                        max_length=16,
                    ),
                ),
                ("salutation", models.CharField(blank=True, max_length=40, null=True)),
                ("first_name", models.CharField(blank=True, max_length=120, null=True)),
                ("last_name", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Firmenkurzname für die Ordnerbenennung (B-20)",
                        max_length=60,
                        null=True,
                    ),
                ),
                ("search_name", models.CharField(max_length=240)),
                ("email", models.CharField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("mobile", models.CharField(blank=True, max_length=40, null=True)),
                ("iban_last4", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "iban_encrypted",
                    objektakte.db.VarBinaryField(blank=True, max_length=160, null=True),
                ),
                (
                    "iban_key_version",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "iban_hash",
                    objektakte.db.VarBinaryField(blank=True, max_length=32, null=True),
                ),
                ("sepa_mandate_present", models.BooleanField(blank=True, null=True)),
                (
                    "sepa_mandate_reference",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "bestätigt"),
                            ("ai_suggested", "KI-Vorschlag"),
                            ("incomplete", "unvollständig"),
                        ],
                        default="incomplete",
                        max_length=16,
                    ),
                ),
                (
                    "correspondence_street",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "correspondence_house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "correspondence_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "correspondence_city",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "correspondence_country",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "correspondence_addition",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "delivery_street",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "delivery_house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "delivery_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "delivery_city",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "delivery_country",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "delivery_addition",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "owners",
                "ordering": ["search_name"],
            },
        ),
        migrations.CreateModel(
            name="OwnerFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "file_kind",
                    models.CharField(
                        choices=[
                            ("unit_owner", "Einheit und Eigentümer"),
                            ("unknown_unit", "Einheit unbekannt"),
                            ("unassigned", "Unzugeordnet"),
                        ],
                        default="unit_owner",
                        max_length=16,
                    ),
                ),
                ("folder_name", models.CharField(max_length=255)),
                ("name_basis", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=16)),
                (
                    "active_key",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(deleted_at__isnull=True, then=models.F("folder_name")),
                            default=models.Value(None),
                        ),
                        output_field=models.CharField(max_length=255, null=True),
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_files",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_id",
                        help_text="nur bei file_kind unknown_unit (B-24)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unknown_unit_files",
                        to="parties.owner",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="unit_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_files",
                        to="objects.unit",
                    ),
                ),
            ],
            options={
                "db_table": "owner_files",
            },
        ),
        migrations.CreateModel(
            name="OwnerUnitAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Eigentumsbeginn einschließlich, leer bedeutet unbekannt",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="Eigentumsende einschließlich, leer bedeutet aktuell",
                        null=True,
                    ),
                ),
                (
                    "share",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "bestätigt"),
                            ("ai_suggested", "KI-Vorschlag"),
                            ("incomplete", "unvollständig"),
                        ],
                        default="incomplete",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "balance_at_takeover",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "is_current",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(then=models.Value(True), valid_to__isnull=True),
                            default=models.Value(False),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="confirmed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="parties.owner",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "source_import_row",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_import_row_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="imports.importrow",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_assignments",
                        to="objects.unit",
                    ),
                ),
            ],
            options={
                "db_table": "owner_unit_assignments",
                "ordering": ["unit_id", "valid_from"],
            },
        ),
        migrations.CreateModel(
            name="OwnerFileAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner_file",
                    models.ForeignKey(
                        db_column="owner_file_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_assignments",
                        to="parties.ownerfile",
                    ),
                ),
                (
                    "assignment",
                    models.OneToOneField(
                        db_column="assignment_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_file_assignment",
                        to="parties.ownerunitassignment",
                    ),
                ),
            ],
            options={
                "db_table": "owner_file_assignments",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("natural_person", "natürliche Person"),
                            ("legal_entity", "juristische Person"),
                            ("community", "Gemeinschaft"),
                        ],
                        max_length=16,
                    ),
                ),
                ("salutation", models.CharField(blank=True, max_length=40, null=True)),
                ("first_name", models.CharField(blank=True, max_length=120, null=True)),
                ("last_name", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Firmenkurzname für die Ordnerbenennung (B-20)",
                        max_length=60,
                        null=True,
                    ),
                ),
                ("search_name", models.CharField(max_length=240)),
                ("email", models.CharField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("mobile", models.CharField(blank=True, max_length=40, null=True)),
                ("iban_last4", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "iban_encrypted",
                    objektakte.db.VarBinaryField(blank=True, max_length=160, null=True),
                ),
                (
                    "iban_key_version",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "iban_hash",
                    objektakte.db.VarBinaryField(blank=True, max_length=32, null=True),
                ),
                ("sepa_mandate_present", models.BooleanField(blank=True, null=True)),
                (
                    "sepa_mandate_reference",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "bestätigt"),
                            ("ai_suggested", "KI-Vorschlag"),
                            ("incomplete", "unvollständig"),
                        ],
                        default="incomplete",
                        max_length=16,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["search_name"],
            },
        ),
        migrations.CreateModel(
            name="TenantFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_kind", models.CharField(default="unit_tenant", max_length=16)),
                ("folder_name", models.CharField(max_length=255)),
                ("name_basis", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=16)),
                (
                    "active_key",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(deleted_at__isnull=True, then=models.F("folder_name")),
                            default=models.Value(None),
                        ),
                        output_field=models.CharField(max_length=255, null=True),
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_files",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="unit_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_files",
                        to="objects.unit",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_files",
            },
        ),
        migrations.CreateModel(
            name="TenantUnitAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("tenant", "Mieter"),
                            ("co_tenant", "Mitmieter"),
                            ("guarantor", "Bürge"),
                        ],
                        default="tenant",
                        max_length=16,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "bestätigt"),
                            ("ai_suggested", "KI-Vorschlag"),
                            ("incomplete", "unvollständig"),
                        ],
                        default="incomplete",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "is_current",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(then=models.Value(True), valid_to__isnull=True),
                            default=models.Value(False),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="confirmed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        db_column="lease_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="parties.lease",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "source_import_row",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_import_row_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="imports.importrow",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="parties.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_assignments",
                        to="objects.unit",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_unit_assignments",
            },
        ),
        migrations.CreateModel(
            name="TenantFileAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant_file",
                    models.ForeignKey(
                        db_column="tenant_file_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_assignments",
                        to="parties.tenantfile",
                    ),
                ),
                (
                    "assignment",
                    models.OneToOneField(
                        db_column="assignment_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_file_assignment",
                        to="parties.tenantunitassignment",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_file_assignments",
            },
        ),
        migrations.CreateModel(
            name="FieldProvenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("owner", "Eigentümer"),
                            ("unit", "Einheit"),
                            ("owner_unit_assignment", "Eigentümerzuordnung"),
                            ("tenant", "Mieter"),
                            ("lease", "Mietverhältnis"),
                            ("tenant_unit_assignment", "Mieterzuordnung"),
                            ("object", "Objekt"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.PositiveBigIntegerField()),
                ("field_name", models.CharField(max_length=64)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("document", "Dokument"),
                            ("import_row", "Importzeile"),
                            ("manual", "manuell"),
                            ("ai", "KI"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_page_from",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("source_page_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "bestätigt"),
                            ("ai_suggested", "KI-Vorschlag"),
                            ("incomplete", "unvollständig"),
                        ],
                        max_length=16,
                    ),
                ),
                ("set_at", models.DateTimeField()),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="set_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "source_import_row",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_import_row_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="imports.importrow",
                    ),
                ),
            ],
            options={
                "db_table": "field_provenance",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity_type", "entity_id", "field_name"),
                        name="uq_provenance_field",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "source_kind__in",
                                ["document", "import_row", "manual", "ai", "system"],
                            )
                        ),
                        name="ck_provenance_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["confirmed", "ai_suggested", "incomplete"])),
                        name="ck_provenance_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_page_from__isnull", True),
                            ("source_page_to__isnull", True),
                            ("source_page_from__lte", models.F("source_page_to")),
                            _connector="OR",
                        ),
                        name="ck_provenance_pages",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["object", "start_date"], name="ix_leases_object_start"),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_date__isnull", True),
                    ("end_date__isnull", True),
                    ("start_date__lte", models.F("end_date")),
                    _connector="OR",
                ),
                name="ck_leases_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("base_rent__isnull", True),
                        ("base_rent__gte", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("utilities_prepayment__isnull", True),
                        ("utilities_prepayment__gte", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("heating_prepayment__isnull", True),
                        ("heating_prepayment__gte", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("deposit_amount__isnull", True),
                        ("deposit_amount__gte", 0),
                        _connector="OR",
                    ),
                ),
                name="ck_leases_amounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deposit_type__isnull", True),
                    (
                        "deposit_type__in",
                        [
                            "cash_account",
                            "savings_book",
                            "bank_guarantee",
                            "pledge",
                            "insurance",
                            "other",
                            "unknown",
                        ],
                    ),
                    _connector="OR",
                ),
                name="ck_leases_deposit_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rent_adjustment_type__in",
                        ["none", "graduated", "indexed", "unknown"],
                    )
                ),
                name="ck_leases_adjustment",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_status__in", ["confirmed", "ai_suggested", "incomplete"])),
                name="ck_leases_data_status",
            ),
        ),
        migrations.AddIndex(
            model_name="owner",
            index=models.Index(fields=["search_name"], name="ix_owners_search_name"),
        ),
        migrations.AddIndex(
            model_name="owner",
            index=models.Index(fields=["last_name"], name="ix_owners_last_name"),
        ),
        migrations.AddIndex(
            model_name="owner",
            index=models.Index(fields=["company_name"], name="ix_owners_company"),
        ),
        migrations.AddIndex(
            model_name="owner",
            index=models.Index(fields=["iban_hash"], name="ix_owners_iban_hash"),
        ),
        migrations.AddIndex(
            model_name="owner",
            index=models.Index(fields=["email"], name="ix_owners_email"),
        ),
        migrations.AddConstraint(
            model_name="owner",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["natural_person", "legal_entity", "community"])),
                name="ck_owners_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="owner",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_status__in", ["confirmed", "ai_suggested", "incomplete"])),
                name="ck_owners_data_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="owner",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("iban_encrypted__isnull", True),
                        ("iban_key_version__isnull", True),
                    ),
                    models.Q(
                        ("iban_encrypted__isnull", False),
                        ("iban_key_version__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_owners_iban_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="ownerfile",
            index=models.Index(fields=["unit"], name="ix_owner_files_unit"),
        ),
        migrations.AddConstraint(
            model_name="ownerfile",
            constraint=models.UniqueConstraint(
                fields=("object", "active_key"), name="uq_owner_files_name_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerfile",
            constraint=models.CheckConstraint(
                condition=models.Q(("file_kind__in", ["unit_owner", "unknown_unit", "unassigned"])),
                name="ck_owner_files_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerfile",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "closed"])),
                name="ck_owner_files_status",
            ),
        ),
        migrations.AddIndex(
            model_name="ownerunitassignment",
            index=models.Index(fields=["unit", "valid_from", "valid_to"], name="ix_oua_unit_period"),
        ),
        migrations.AddIndex(
            model_name="ownerunitassignment",
            index=models.Index(fields=["owner", "valid_from"], name="ix_oua_owner_period"),
        ),
        migrations.AddIndex(
            model_name="ownerunitassignment",
            index=models.Index(fields=["unit", "is_current"], name="ix_oua_unit_current"),
        ),
        migrations.AddConstraint(
            model_name="ownerunitassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_to__isnull", True),
                    ("valid_from__lte", models.F("valid_to")),
                    _connector="OR",
                ),
                name="ck_oua_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerunitassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("share__isnull", True),
                    models.Q(("share__gt", 0), ("share__lte", 1)),
                    _connector="OR",
                ),
                name="ck_oua_share",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerunitassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_status__in", ["confirmed", "ai_suggested", "incomplete"])),
                name="ck_oua_data_status",
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["search_name"], name="ix_tenants_search_name"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["last_name"], name="ix_tenants_last_name"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["iban_hash"], name="ix_tenants_iban_hash"),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["natural_person", "legal_entity"])),
                name="ck_tenants_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_status__in", ["confirmed", "ai_suggested", "incomplete"])),
                name="ck_tenants_data_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("iban_encrypted__isnull", True),
                        ("iban_key_version__isnull", True),
                    ),
                    models.Q(
                        ("iban_encrypted__isnull", False),
                        ("iban_key_version__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_tenants_iban_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantfile",
            index=models.Index(fields=["unit"], name="ix_tenant_files_unit"),
        ),
        migrations.AddConstraint(
            model_name="tenantfile",
            constraint=models.UniqueConstraint(
                fields=("object", "active_key"), name="uq_tenant_files_name_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantfile",
            constraint=models.CheckConstraint(
                condition=models.Q(("file_kind__in", ["unit_tenant", "unknown_unit", "unassigned"])),
                name="ck_tenant_files_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantfile",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "closed"])),
                name="ck_tenant_files_status",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantunitassignment",
            index=models.Index(fields=["unit", "valid_from", "valid_to"], name="ix_tua_unit_period"),
        ),
        migrations.AddIndex(
            model_name="tenantunitassignment",
            index=models.Index(fields=["tenant", "valid_from"], name="ix_tua_tenant_period"),
        ),
        migrations.AddConstraint(
            model_name="tenantunitassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["tenant", "co_tenant", "guarantor"])),
                name="ck_tua_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantunitassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_to__isnull", True),
                    ("valid_from__lte", models.F("valid_to")),
                    _connector="OR",
                ),
                name="ck_tua_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantunitassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_status__in", ["confirmed", "ai_suggested", "incomplete"])),
                name="ck_tua_data_status",
            ),
        ),
    ]
