# Generated by Django 5.2.17 on 2026-09-12 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ownerfile",
            name="ck_owner_files_kind",
        ),
        migrations.AlterField(
            model_name="ownerfile",
            name="file_kind",
            field=models.CharField(
                choices=[
                    ("unit_owner", "Einheit und Eigentümer"),
                    ("object_owner", "Eigentümer des Objekts"),
                    ("unknown_unit", "Einheit unbekannt"),
                    ("unassigned", "Unzugeordnet"),
                ],
                default="unit_owner",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerfile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "file_kind__in",
                        ["unit_owner", "object_owner", "unknown_unit", "unassigned"],
                    )
                ),
                name="ck_owner_files_kind",
            ),
        ),
    ]
