# Generated by Django 5.2.17 on 2026-09-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrmApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Bezeichnung des Abnehmers, z. B. crm", max_length=80
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hex des Klartexts",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list,
                        help_text="Liste aus objects:read, documents:read, persons:read",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "crm_api_tokens",
                "ordering": ["pk"],
                "indexes": [
                    models.Index(
                        fields=["name", "is_active"], name="ix_crm_tokens_name"
                    )
                ],
            },
        ),
    ]
