# Generated by Django 5.2.17 on 2026-09-26 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_api", "0001_crm_tokens"),
        ("documents", "0008_email_regeln_entscheider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmapitoken",
            name="scopes",
            field=models.JSONField(
                default=list,
                help_text="Liste aus objects:read, documents:read, persons:read, documents:write",
            ),
        ),
        migrations.CreateModel(
            name="CrmUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("crm_document_id", models.CharField(max_length=64, unique=True)),
                ("hints", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.OneToOneField(
                        db_column="document_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crm_upload",
                        to="documents.document",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        db_column="token_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm_api.crmapitoken",
                    ),
                ),
            ],
            options={
                "db_table": "crm_uploads",
                "ordering": ["pk"],
            },
        ),
    ]
