# Generated by Django 5.2.17 on 2026-09-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0002_crm_uploads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmapitoken",
            name="scopes",
            field=models.JSONField(
                default=list,
                help_text="Liste aus objects:read, documents:read, persons:read, documents:write, persons:write",
            ),
        ),
    ]
