# Generated by Django 5.2.17 on 2026-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("classify", "Klassifikation"),
                            ("extract_entities", "Entitäten"),
                            ("parse_list", "Liste einlesen"),
                            ("other", "sonstiges"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        max_length=24,
                    ),
                ),
                ("model", models.CharField(max_length=80)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("region", models.CharField(blank=True, max_length=40, null=True)),
                ("page_from", models.PositiveIntegerField(blank=True, null=True)),
                ("page_to", models.PositiveIntegerField(blank=True, null=True)),
                ("prompt_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("prompt_chars", models.PositiveIntegerField(blank=True, null=True)),
                ("masked_entities_count", models.PositiveSmallIntegerField(default=0)),
                ("tokens_in", models.PositiveIntegerField(blank=True, null=True)),
                ("tokens_out", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost_eur",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "price_list_version",
                    models.CharField(blank=True, max_length=24, null=True),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "ok"),
                            ("error", "Fehler"),
                            ("timeout", "Zeitüberschreitung"),
                            ("rate_limited", "Ratenbegrenzung"),
                            ("budget_blocked", "Kostenlimit"),
                            ("schema_error", "Antwortschema verletzt"),
                            ("provider_error", "Anbieterfehler"),
                            (
                                "blocked_by_mask_check",
                                "durch Maskierungsprüfung gesperrt",
                            ),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("fallback_used", models.BooleanField(default=False)),
                ("response_summary", models.JSONField(blank=True, null=True)),
                ("requested_at", models.DateTimeField()),
            ],
            options={
                "db_table": "ai_calls",
            },
        ),
    ]
