# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("documents", "0001_initial"),
        ("objects", "0001_initial"),
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicall",
            name="document",
            field=models.ForeignKey(
                blank=True,
                db_column="document_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_calls",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="aicall",
            name="fallback_of_call",
            field=models.ForeignKey(
                blank=True,
                db_column="fallback_of_call_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fallbacks",
                to="ai.aicall",
            ),
        ),
        migrations.AddField(
            model_name="aicall",
            name="job",
            field=models.ForeignKey(
                blank=True,
                db_column="job_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_calls",
                to="pipeline.processingjob",
            ),
        ),
        migrations.AddField(
            model_name="aicall",
            name="object",
            field=models.ForeignKey(
                blank=True,
                db_column="object_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_calls",
                to="objects.managedobject",
            ),
        ),
        migrations.AddField(
            model_name="aicall",
            name="run",
            field=models.ForeignKey(
                blank=True,
                db_column="run_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_calls",
                to="pipeline.processingrun",
            ),
        ),
        migrations.AddIndex(
            model_name="aicall",
            index=models.Index(fields=["object", "requested_at"], name="ix_ai_calls_object_time"),
        ),
        migrations.AddIndex(
            model_name="aicall",
            index=models.Index(fields=["provider", "requested_at"], name="ix_ai_calls_provider_time"),
        ),
        migrations.AddIndex(
            model_name="aicall",
            index=models.Index(fields=["status", "requested_at"], name="ix_ai_calls_status"),
        ),
        migrations.AddConstraint(
            model_name="aicall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "purpose__in",
                        ["classify", "extract_entities", "parse_list", "other"],
                    )
                ),
                name="ck_ai_calls_purpose",
            ),
        ),
        migrations.AddConstraint(
            model_name="aicall",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider__in", ["openai", "anthropic"])),
                name="ck_ai_calls_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="aicall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "ok",
                            "error",
                            "timeout",
                            "rate_limited",
                            "budget_blocked",
                            "schema_error",
                            "provider_error",
                            "blocked_by_mask_check",
                        ],
                    )
                ),
                name="ck_ai_calls_status",
            ),
        ),
    ]
