# Generated by Django 5.2.17 on 2026-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_fremdschluessel"),
        ("documents", "0006_dokument_uuid_quelle_paperless"),
        ("objects", "0003_weitere_anschriften"),
        ("pipeline", "0004_job_versandzeit"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aicall",
            name="ck_ai_calls_purpose",
        ),
        migrations.AlterField(
            model_name="aicall",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("classify", "Klassifikation"),
                    ("extract_entities", "Entitäten"),
                    ("parse_list", "Liste einlesen"),
                    ("assign_object", "Objektzuordnung"),
                    ("other", "sonstiges"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="aicall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "purpose__in",
                        [
                            "classify",
                            "extract_entities",
                            "parse_list",
                            "assign_object",
                            "other",
                        ],
                    )
                ),
                name="ck_ai_calls_purpose",
            ),
        ),
    ]
