# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("objects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("full", "Vollverarbeitung"),
                            ("incremental", "Nachlauf"),
                            ("reconcile_drive", "Ordnerabgleich"),
                            ("regenerate_lists", "Listen erzeugen"),
                            ("reclassify", "Neu klassifizieren"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "wartet"),
                            ("running", "läuft"),
                            ("done", "fertig"),
                            ("failed", "fehlgeschlagen"),
                            ("aborted", "abgebrochen"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                (
                    "worker_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("documents_total", models.PositiveIntegerField(blank=True, null=True)),
                ("documents_done", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "documents_failed",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "documents_skipped",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("pages_total", models.PositiveIntegerField(blank=True, null=True)),
                ("pages_done", models.PositiveIntegerField(blank=True, null=True)),
                ("documents_misc", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "misc_share_pct",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "pages_per_minute",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("ram_peak_mb", models.PositiveIntegerField(blank=True, null=True)),
                ("ai_calls_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ai_cost_eur",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "ai_fallback_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "review_cases_created",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_runs",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="triggered_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "processing_runs",
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("discover", "Inventur"),
                            ("hash", "Download und Hash"),
                            ("analyze_pages", "Seitenanalyse"),
                            ("ocr_chunk", "OCR je Block"),
                            ("merge_pages", "Seiten zusammenführen"),
                            ("render_previews", "Vorschauen"),
                            ("extract_entities", "Entitäten erkennen"),
                            ("classify", "Klassifikation Stufe 1 und 2"),
                            ("classify_ai", "Klassifikation Stufe 3"),
                            ("decide", "Entscheidung"),
                            ("file_to_drive", "Ablage in Drive"),
                            ("link_segments", "Seitenbereiche verknüpfen"),
                            ("generate_lists", "Listen erzeugen"),
                            ("evaluate_completeness", "Vollständigkeit prüfen"),
                            ("reconcile_drive", "Ordnerabgleich"),
                            ("train_classifier", "Klassifikator trainieren"),
                            ("sweep", "Sweeper"),
                        ],
                        max_length=24,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "wartet"),
                            ("running", "läuft"),
                            ("done", "fertig"),
                            ("failed", "fehlgeschlagen"),
                            ("skipped", "übersprungen"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=100)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("locked_by", models.CharField(blank=True, max_length=80, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("pages_processed", models.PositiveIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("error_class", models.CharField(blank=True, max_length=80, null=True)),
                ("skip_reason", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="documents.document",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_jobs",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        db_column="run_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="pipeline.processingrun",
                    ),
                ),
            ],
            options={
                "db_table": "processing_jobs",
            },
        ),
        migrations.CreateModel(
            name="ObjectProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documents_total", models.PositiveIntegerField(default=0)),
                ("documents_hashed", models.PositiveIntegerField(default=0)),
                ("documents_ocr_done", models.PositiveIntegerField(default=0)),
                ("documents_classified", models.PositiveIntegerField(default=0)),
                ("documents_filed", models.PositiveIntegerField(default=0)),
                ("documents_review", models.PositiveIntegerField(default=0)),
                ("documents_duplicate", models.PositiveIntegerField(default=0)),
                ("documents_error", models.PositiveIntegerField(default=0)),
                ("documents_misc", models.PositiveIntegerField(default=0)),
                ("pages_total", models.PositiveIntegerField(default=0)),
                ("pages_done", models.PositiveIntegerField(default=0)),
                ("review_open", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object",
                    models.OneToOneField(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "last_run",
                    models.ForeignKey(
                        blank=True,
                        db_column="last_run_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pipeline.processingrun",
                    ),
                ),
            ],
            options={
                "db_table": "object_progress",
            },
        ),
        migrations.CreateModel(
            name="ProcessingJobEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=16, null=True)),
                ("to_status", models.CharField(max_length=16)),
                ("worker_id", models.CharField(blank=True, max_length=80, null=True)),
                ("attempt_no", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        db_column="job_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="pipeline.processingjob",
                    ),
                ),
            ],
            options={
                "db_table": "processing_job_events",
                "indexes": [models.Index(fields=["job", "created_at"], name="ix_job_events_job")],
            },
        ),
        migrations.AddIndex(
            model_name="processingrun",
            index=models.Index(fields=["object", "started_at"], name="ix_runs_object_started"),
        ),
        migrations.AddIndex(
            model_name="processingrun",
            index=models.Index(fields=["status"], name="ix_runs_status"),
        ),
        migrations.AddConstraint(
            model_name="processingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "run_type__in",
                        [
                            "full",
                            "incremental",
                            "reconcile_drive",
                            "regenerate_lists",
                            "reclassify",
                        ],
                    )
                ),
                name="ck_runs_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="processingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "running", "done", "failed", "aborted"])),
                name="ck_runs_status",
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["status", "next_attempt_at", "priority", "id"],
                name="ix_jobs_pickup",
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["run", "status"], name="ix_jobs_run_status"),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["status", "heartbeat_at"], name="ix_jobs_stale"),
        ),
        migrations.AddConstraint(
            model_name="processingjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "job_type__in",
                        [
                            "discover",
                            "hash",
                            "analyze_pages",
                            "ocr_chunk",
                            "merge_pages",
                            "render_previews",
                            "extract_entities",
                            "classify",
                            "classify_ai",
                            "decide",
                            "file_to_drive",
                            "link_segments",
                            "generate_lists",
                            "evaluate_completeness",
                            "reconcile_drive",
                            "train_classifier",
                            "sweep",
                        ],
                    )
                ),
                name="ck_jobs_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="processingjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "running", "done", "failed", "skipped"])),
                name="ck_jobs_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="processingjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "attempt_count__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("max_attempts"), "+", models.Value(1)
                        ),
                    )
                ),
                name="ck_jobs_attempts",
            ),
        ),
    ]
