# Generated by Django 5.2.17 on 2026-09-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingrun",
            name="misc_share_adjusted_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Anteil 06 ohne 03_Dubletten, 04_Nicht_objektbezogen und Fälle mit fachlichem Grund (B-31)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
