# Generated by Django 5.2.17 on 2026-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_dokument_uuid_quelle_paperless"),
        ("objects", "0002_eingangsobjekt"),
        ("pipeline", "0002_regeldefinition_kpi"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="processingjob",
            name="ck_jobs_type",
        ),
        migrations.AlterField(
            model_name="processingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("discover", "Inventur"),
                    ("hash", "Download und Hash"),
                    ("analyze_pages", "Seitenanalyse"),
                    ("ocr_chunk", "OCR je Block"),
                    ("merge_pages", "Seiten zusammenführen"),
                    ("render_previews", "Vorschauen"),
                    ("extract_entities", "Entitäten erkennen"),
                    ("classify", "Klassifikation Stufe 1 und 2"),
                    ("classify_ai", "Klassifikation Stufe 3"),
                    ("decide", "Entscheidung"),
                    ("file_to_drive", "Ablage in Drive"),
                    ("assign_object", "Objektzuordnung"),
                    ("link_segments", "Seitenbereiche verknüpfen"),
                    ("generate_lists", "Listen erzeugen"),
                    ("evaluate_completeness", "Vollständigkeit prüfen"),
                    ("reconcile_drive", "Ordnerabgleich"),
                    ("train_classifier", "Klassifikator trainieren"),
                    ("sweep", "Sweeper"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="processingjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "job_type__in",
                        [
                            "discover",
                            "hash",
                            "analyze_pages",
                            "ocr_chunk",
                            "merge_pages",
                            "render_previews",
                            "extract_entities",
                            "classify",
                            "classify_ai",
                            "decide",
                            "file_to_drive",
                            "assign_object",
                            "link_segments",
                            "generate_lists",
                            "evaluate_completeness",
                            "reconcile_drive",
                            "train_classifier",
                            "sweep",
                        ],
                    )
                ),
                name="ck_jobs_type",
            ),
        ),
    ]
