# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models

import objektakte.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0002_fremdschluessel_ai_drive_objects"),
        ("objects", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestTextBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("text", models.TextField()),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "request_text_blocks",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="CompletenessFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_code", models.CharField(max_length=48)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("object", "Objekt"),
                            ("unit", "Einheit"),
                            ("assignment", "Zuordnung"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "period_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("missing", "fehlt"),
                            ("partial", "teilweise"),
                            ("fulfilled", "erfüllt"),
                            ("not_applicable", "nicht anwendbar"),
                        ],
                        max_length=16,
                    ),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("include_in_request", models.BooleanField(default=True)),
                (
                    "manual_status",
                    models.CharField(
                        blank=True,
                        help_text="Negativerklärung: fulfilled oder not_applicable",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "manual_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("manual_at", models.DateTimeField(blank=True, null=True)),
                ("last_evaluated_at", models.DateTimeField()),
                (
                    "position_key",
                    models.GeneratedField(
                        db_persist=True,
                        expression=objektakte.db.ConcatWS(
                            models.Value("|"),
                            models.F("check_code"),
                            models.F("scope_type"),
                            django.db.models.functions.comparison.Coalesce(
                                models.F("unit_id"),
                                models.Value(0),
                                output_field=models.IntegerField(),
                            ),
                            django.db.models.functions.comparison.Coalesce(
                                models.F("assignment_id"),
                                models.Value(0),
                                output_field=models.IntegerField(),
                            ),
                            django.db.models.functions.comparison.Coalesce(
                                models.F("period_year"),
                                models.Value(0),
                                output_field=models.IntegerField(),
                            ),
                        ),
                        output_field=models.CharField(max_length=120),
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        db_column="assignment_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="parties.ownerunitassignment",
                    ),
                ),
                (
                    "evidence_document",
                    models.ForeignKey(
                        blank=True,
                        db_column="evidence_document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "evidence_link",
                    models.ForeignKey(
                        blank=True,
                        db_column="evidence_link_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentownerlink",
                    ),
                ),
                (
                    "manual_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="manual_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="unit_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="objects.unit",
                    ),
                ),
            ],
            options={
                "db_table": "completeness_findings",
                "indexes": [models.Index(fields=["object", "status"], name="ix_findings_status")],
                "constraints": [
                    models.UniqueConstraint(fields=("object", "position_key"), name="uq_findings_position"),
                    models.CheckConstraint(
                        condition=models.Q(("scope_type__in", ["object", "unit", "assignment"])),
                        name="ck_findings_scope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["missing", "partial", "fulfilled", "not_applicable"],
                            )
                        ),
                        name="ck_findings_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("manual_status__isnull", True),
                            ("manual_status__in", ["fulfilled", "not_applicable"]),
                            _connector="OR",
                        ),
                        name="ck_findings_manual",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("approved", "freigegeben"),
                            ("sent", "versendet (manuell)"),
                            ("withdrawn", "zurückgezogen"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=160)),
                (
                    "recipient_street",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "recipient_house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "recipient_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "recipient_city",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "recipient_contact_person",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("reference", models.CharField(blank=True, max_length=80, null=True)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("finding_ids", models.JSONField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=255, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="approved_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_requests",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="withdrawn_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_requests",
                "indexes": [models.Index(fields=["object", "status"], name="ix_requests_object_status")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["draft", "approved", "sent", "withdrawn"])),
                        name="ck_requests_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompletenessCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("object", "Objekt"),
                            ("unit", "Einheit"),
                            ("assignment", "Zuordnung"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "management_types",
                    models.JSONField(
                        blank=True,
                        help_text="Verwaltungsarten, für die der Prüfpunkt gilt; leer bedeutet alle",
                        null=True,
                    ),
                ),
                ("period_based", models.BooleanField(default=False)),
                (
                    "evidence_document_types",
                    models.JSONField(
                        blank=True,
                        help_text="Codes aus document_types, die den Punkt belegen",
                        null=True,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "request_text_block",
                    models.ForeignKey(
                        blank=True,
                        db_column="request_text_block_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checks",
                        to="requirements.requesttextblock",
                    ),
                ),
            ],
            options={
                "db_table": "completeness_checks",
                "ordering": ["sort_order", "code"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("scope_type__in", ["object", "unit", "assignment"])),
                        name="ck_checks_scope",
                    )
                ],
            },
        ),
    ]
