# Generated by Django 5.2.17 on 2026-09-10 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_regeldefinition_kpi"),
        ("objects", "0001_initial"),
        ("requirements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentrequest",
            name="ck_requests_status",
        ),
        migrations.AddField(
            model_name="completenesscheck",
            name="blocking",
            field=models.BooleanField(
                default=False,
                help_text="Fehlen verhindert die Einstufung weitgehend vollständig",
            ),
        ),
        migrations.AddField(
            model_name="completenesscheck",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Gruppe im Nachforderungsschreiben (H 4.2 Nr. 6)",
                max_length=48,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="custom_text_blocks",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="deadline_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="docx_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="findings_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Positionen zum Erzeugungszeitpunkt (H 4.1)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="marked_sent_by",
            field=models.ForeignKey(
                blank=True,
                db_column="marked_sent_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="pdf_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                db_column="reviewed_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="sent_channel_note",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="text_block_versions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="requesttextblock",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="requesttextblock",
            name="version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="completenessfinding",
            name="evidence_document",
            field=models.ForeignKey(
                blank=True,
                db_column="evidence_document_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.document",
            ),
        ),
        migrations.AlterField(
            model_name="completenessfinding",
            name="evidence_link",
            field=models.ForeignKey(
                blank=True,
                db_column="evidence_link_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.documentownerlink",
            ),
        ),
        migrations.AlterField(
            model_name="documentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("reviewed", "geprüft"),
                    ("approved", "freigegeben"),
                    ("sent", "als versendet vermerkt"),
                    ("withdrawn", "zurückgezogen"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="documentrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "reviewed", "approved", "sent", "withdrawn"],
                    )
                ),
                name="ck_requests_status",
            ),
        ),
    ]
