# Generated by Django 5.2.17 on 2026-09-12 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_regeldefinition_kpi"),
        ("objects", "0001_initial"),
        ("parties", "0002_owner_file_kind_object_owner"),
        ("requirements", "0002_nachforderung_pruefkatalog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="completenessfinding",
            name="ck_findings_manual",
        ),
        migrations.AddConstraint(
            model_name="completenessfinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("manual_status__isnull", True),
                    ("manual_status__in", ["fulfilled", "partial", "not_applicable"]),
                    _connector="OR",
                ),
                name="ck_findings_manual",
            ),
        ),
    ]
