# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("drive", "0001_initial"),
        ("objects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_type", models.CharField(max_length=16)),
                ("list_format", models.CharField(max_length=8)),
                (
                    "trigger_kind",
                    models.CharField(
                        choices=[
                            ("run", "Verarbeitungslauf"),
                            ("review_confirm", "Review-Bestätigung"),
                            ("manual", "manuell"),
                            ("import_commit", "Import übernommen"),
                            ("masterdata_change", "Stammdatenänderung"),
                            ("scheduled", "Zeitplan"),
                        ],
                        max_length=24,
                    ),
                ),
                ("rows_current", models.PositiveIntegerField(blank=True, null=True)),
                ("rows_history", models.PositiveIntegerField(blank=True, null=True)),
                ("rows_open", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "fertig"),
                            ("failed", "fehlgeschlagen"),
                            ("skipped_unchanged", "unverändert übersprungen"),
                        ],
                        max_length=24,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("generated_at", models.DateTimeField()),
                (
                    "drive_node",
                    models.ForeignKey(
                        blank=True,
                        db_column="drive_node_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="drive.drivenode",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="list_generations",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="triggered_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "list_generations",
                "indexes": [
                    models.Index(
                        fields=["object", "list_type", "list_format", "generated_at"],
                        name="ix_list_gen_object",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("list_type__in", ["owner_list", "tenant_list"])),
                        name="ck_list_gen_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("list_format__in", ["xlsx", "pdf"])),
                        name="ck_list_gen_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "trigger_kind__in",
                                [
                                    "run",
                                    "review_confirm",
                                    "manual",
                                    "import_commit",
                                    "masterdata_change",
                                    "scheduled",
                                ],
                            )
                        ),
                        name="ck_list_gen_trigger",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["done", "failed", "skipped_unchanged"])),
                        name="ck_list_gen_status",
                    ),
                ],
            },
        ),
    ]
