"""Register der Audit-Aktionen (docs/architektur.md 5.7, Anhang D.6). Neue Aktionen werden hier eingetragen;
das Bezeichnerregister (docs/architektur/bezeichnerregister.md) wird daraus erzeugt."""

AUDIT_ACTIONS: dict[str, str] = {
    "auth.login": "Anmeldung",
    "auth.login_failed": "fehlgeschlagene Anmeldung",
    "auth.denied": "verweigerter Zugriff (fehlendes Recht)",
    "auth.totp_reset": "zweiter Faktor zurückgesetzt",
    "user.create": "Nutzer angelegt",
    "user.status": "Nutzer gesperrt oder entsperrt",
    "user.role": "Rolle geändert",
    "user.unlock": "Sperre nach Fehlversuchen aufgehoben",
    "setting.update": "Konfigurationswert geändert",
    "setting.seed": "Konfigurationswert durch Seed überschrieben",
    "object.create": "Objekt angelegt",
    "object.update": "Objekt geändert",
    "unit.create": "Einheit angelegt",
    "unit.update": "Einheit geändert",
    "owner.create": "Eigentümer angelegt",
    "owner.update": "Eigentümer geändert",
    "assignment.create": "Zuordnung Eigentümer zu Einheit angelegt",
    "assignment.end": "Zuordnung beendet (Eigentümerwechsel)",
    "drive.authorize": "Google-Verbindung hergestellt",
    "drive.token_refresh": "Token erneuert",
    "drive.reconcile": "Ordnerabgleich angestoßen",
    "drive.rename": "Ordner in Drive umbenannt",
    "drive.move": "Datei in Drive verschoben",
    "drive.create_folder": "Ordner in Drive angelegt",
    "drive.upload": "Datei nach Drive hochgeladen",
    "document.view": "Dokument aus Eigentümerakte angesehen (nur bei security.log_document_views)",
    "document.download": "Dokument aus Eigentümerakte heruntergeladen (nur bei security.log_document_views)",
    "review.assign": "Fall zugewiesen",
    "review.confirm": "Vorschlag bestätigt",
    "review.reclassify": "neu klassifiziert",
    "review.merge_duplicate": "Dublette zusammengeführt",
    "review.split": "Dokument aufgeteilt",
    "review.defer": "Fall zurückgestellt",
    "review.dismiss": "Fall verworfen",
    "review.reopen": "Fall wiedereröffnet",
    "review.bulk_execute": "Massenbearbeitung ausgeführt",
    "review.transfer_object": "in anderes Objekt übernommen",
    "review.dismiss_object_case": "Fall zur Objektzuordnung verworfen (nur Admin)",
    "import.upload": "Importdatei angenommen",
    "import.parse": "Importzeilen erkannt",
    "import.row_commit": "Importzeile übernommen oder abgelehnt",
    "import.commit": "Import übernommen (Lauf)",
    "import.rollback": "Import zurückgenommen",
    "retention.approve": "Aufbewahrungsfrist freigegeben",
    "deletion.propose": "Löschvorschlag erzeugt",
    "deletion.execute": "Löschung ausgeführt",
    "list.generate": "Liste erzeugt",
    "list.export": "Liste heruntergeladen",
    "request.approve": "Nachforderung freigegeben",
    "request.withdraw": "Nachforderung zurückgezogen",
}
