# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0002_fremdschluessel_ai_drive_objects"),
        ("drive", "0001_initial"),
        ("imports", "0001_initial"),
        ("objects", "0001_initial"),
        ("parties", "0001_initial"),
        ("pipeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("owner_candidates", "Eigentümer mehrdeutig"),
                            ("missing_metadata", "Pflichtmetadatum fehlt"),
                            ("move_proposal", "Verschiebevorschlag"),
                            ("drive_structure", "Ordnerstruktur"),
                            ("import_row_uncertain", "Importzeile unsicher"),
                            ("import_candidate", "Liste erkannt"),
                            ("duplicate_object_number", "Objektnummer doppelt"),
                            ("data_consistency", "Stammdaten widersprüchlich"),
                            ("unclear", "unklar"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "case_subtype",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("page_from", models.PositiveIntegerField(blank=True, null=True)),
                ("page_to", models.PositiveIntegerField(blank=True, null=True)),
                ("candidates", models.JSONField(blank=True, null=True)),
                ("proposed_action", models.JSONField(blank=True, null=True)),
                ("context", models.JSONField(blank=True, null=True)),
                ("batch_key", models.CharField(blank=True, max_length=120, null=True)),
                ("priority", models.SmallIntegerField(default=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "offen"),
                            ("in_progress", "in Bearbeitung"),
                            ("resolved", "erledigt"),
                            ("dismissed", "verworfen"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.JSONField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        db_column="assigned_to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_run",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_run_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pipeline.processingrun",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_cases",
                        to="documents.document",
                    ),
                ),
                (
                    "drive_node",
                    models.ForeignKey(
                        blank=True,
                        db_column="drive_node_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="drive.drivenode",
                    ),
                ),
                (
                    "import_row",
                    models.ForeignKey(
                        blank=True,
                        db_column="import_row_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="imports.importrow",
                    ),
                ),
                (
                    "misc_subfolder",
                    models.ForeignKey(
                        blank=True,
                        db_column="misc_subfolder_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentsubfolder",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        blank=True,
                        db_column="object_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_cases",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "owner_link",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_link_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentownerlink",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="resolved_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "review_cases",
            },
        ),
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_from", models.PositiveIntegerField(blank=True, null=True)),
                ("page_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("confirm", "bestätigen"),
                            ("correct", "korrigieren"),
                            ("reject", "ablehnen"),
                            ("move", "verschieben"),
                            ("assign_owner", "Eigentümer zuordnen"),
                            ("assign_tenant", "Mieter zuordnen"),
                            ("split", "aufteilen"),
                            ("merge", "zusammenführen"),
                            ("select_folder", "Ordner wählen"),
                            ("transfer_object", "in anderes Objekt übernehmen"),
                            ("revert", "zurücknehmen"),
                        ],
                        max_length=24,
                    ),
                ),
                ("decided_at", models.DateTimeField()),
                ("is_bulk", models.BooleanField(default=False)),
                ("bulk_key", models.CharField(blank=True, max_length=120, null=True)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField()),
                ("features_snapshot", models.JSONField(blank=True, null=True)),
                ("text_hashes", models.JSONField(blank=True, null=True)),
                (
                    "label_period_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("label_scope", models.CharField(blank=True, max_length=16, null=True)),
                ("system_was_correct", models.BooleanField(blank=True, null=True)),
                ("used_for_training", models.BooleanField(default=False)),
                (
                    "training_export_ref",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("comment", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        db_column="decided_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "label_assignment",
                    models.ForeignKey(
                        blank=True,
                        db_column="label_assignment_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="parties.ownerunitassignment",
                    ),
                ),
                (
                    "label_category",
                    models.ForeignKey(
                        blank=True,
                        db_column="label_category_code",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentcategory",
                    ),
                ),
                (
                    "label_document_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="label_document_type_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documenttype",
                    ),
                ),
                (
                    "label_owner",
                    models.ForeignKey(
                        blank=True,
                        db_column="label_owner_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="parties.owner",
                    ),
                ),
                (
                    "label_subfolder",
                    models.ForeignKey(
                        blank=True,
                        db_column="label_subfolder_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentsubfolder",
                    ),
                ),
                (
                    "label_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="label_unit_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="objects.unit",
                    ),
                ),
                (
                    "review_case",
                    models.ForeignKey(
                        db_column="review_case_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="review.reviewcase",
                    ),
                ),
            ],
            options={
                "db_table": "review_decisions",
            },
        ),
        migrations.CreateModel(
            name="ReviewSavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("filters", models.JSONField()),
                ("is_shared", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "review_saved_filters",
            },
        ),
        migrations.AddIndex(
            model_name="reviewcase",
            index=models.Index(fields=["object", "status", "case_type"], name="ix_review_object_status"),
        ),
        migrations.AddIndex(
            model_name="reviewcase",
            index=models.Index(fields=["status", "priority", "created_at"], name="ix_review_queue"),
        ),
        migrations.AddIndex(
            model_name="reviewcase",
            index=models.Index(fields=["batch_key"], name="ix_review_batch"),
        ),
        migrations.AddIndex(
            model_name="reviewcase",
            index=models.Index(fields=["assigned_to", "status"], name="ix_review_assigned"),
        ),
        migrations.AddConstraint(
            model_name="reviewcase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "case_type__in",
                        [
                            "owner_candidates",
                            "missing_metadata",
                            "move_proposal",
                            "drive_structure",
                            "import_row_uncertain",
                            "import_candidate",
                            "duplicate_object_number",
                            "data_consistency",
                            "unclear",
                        ],
                    )
                ),
                name="ck_review_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcase",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "in_progress", "resolved", "dismissed"])),
                name="ck_review_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("page_from__isnull", True),
                    ("page_to__isnull", True),
                    ("page_from__lte", models.F("page_to")),
                    _connector="OR",
                ),
                name="ck_review_pages",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewdecision",
            index=models.Index(
                fields=["used_for_training", "label_category"],
                name="ix_decisions_training",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewdecision",
            index=models.Index(fields=["decided_by", "decided_at"], name="ix_decisions_user"),
        ),
        migrations.AddConstraint(
            model_name="reviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "decision_type__in",
                        [
                            "confirm",
                            "correct",
                            "reject",
                            "move",
                            "assign_owner",
                            "assign_tenant",
                            "split",
                            "merge",
                            "select_folder",
                            "transfer_object",
                            "revert",
                        ],
                    )
                ),
                name="ck_decisions_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("label_scope__isnull", True),
                    ("label_scope__in", ["object", "accounting", "owner", "tenant"]),
                    _connector="OR",
                ),
                name="ck_decisions_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewsavedfilter",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="uq_review_filters_user_name"),
        ),
    ]
