# Generated by Django 5.2.17 on 2026-09-12 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_dokument_uuid_quelle_paperless"),
        ("drive", "0003_takeover_sources"),
        ("imports", "0002_fremdschluessel"),
        ("objects", "0002_eingangsobjekt"),
        ("pipeline", "0003_job_objektzuordnung"),
        ("review", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reviewcase",
            name="ck_review_type",
        ),
        migrations.AlterField(
            model_name="reviewcase",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("owner_candidates", "Eigentümer mehrdeutig"),
                    ("missing_metadata", "Pflichtmetadatum fehlt"),
                    ("move_proposal", "Verschiebevorschlag"),
                    ("drive_structure", "Ordnerstruktur"),
                    ("import_row_uncertain", "Importzeile unsicher"),
                    ("import_candidate", "Liste erkannt"),
                    ("duplicate_object_number", "Objektnummer doppelt"),
                    ("data_consistency", "Stammdaten widersprüchlich"),
                    ("object_assignment", "Objektzuordnung"),
                    ("sync_conflict", "Abgleichskonflikt"),
                    ("unclear", "unklar"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "case_type__in",
                        [
                            "owner_candidates",
                            "missing_metadata",
                            "move_proposal",
                            "drive_structure",
                            "import_row_uncertain",
                            "import_candidate",
                            "duplicate_object_number",
                            "data_consistency",
                            "object_assignment",
                            "sync_conflict",
                            "unclear",
                        ],
                    )
                ),
                name="ck_review_type",
            ),
        ),
    ]
