# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "rule_kind",
                    models.CharField(
                        choices=[
                            ("filename", "Dateiname"),
                            ("folder", "Herkunftsordner"),
                            ("keyword", "Stichwort im Text"),
                            ("entity", "erkannte Entität"),
                            ("period", "Zeitbezug"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "pattern",
                    models.TextField(help_text="regulärer Ausdruck oder Stichwortliste, je rule_kind"),
                ),
                (
                    "scope_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("object", "Objekt"),
                            ("accounting", "Buchhaltung"),
                            ("owner", "Eigentümer"),
                            ("tenant", "Mieter"),
                            ("unclear", "unklar"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=4, default=1, max_digits=5),
                ),
                (
                    "is_hard",
                    models.BooleanField(default=False, help_text="harter Treffer mit Konfidenz 1,0"),
                ),
                (
                    "management_types",
                    models.JSONField(
                        blank=True,
                        help_text="Verwaltungsarten, für die die Regel gilt; leer bedeutet alle",
                        null=True,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "classification_rules",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("folder_name", models.CharField(max_length=80, unique=True)),
                ("display_name", models.CharField(max_length=80)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("object", "Objekt"),
                            ("owner", "Eigentümer"),
                            ("tenant", "Mieter"),
                            ("misc", "Sonstiges"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "document_categories",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="DocumentClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_from", models.PositiveIntegerField(blank=True, null=True)),
                ("page_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "stage",
                    models.PositiveSmallIntegerField(
                        help_text="1 Regelwerk, 2 lokal, 3 externe KI, 4 Mensch"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("rules", "Regelwerk"),
                            ("local_model", "lokales Modell"),
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("human", "Mensch"),
                        ],
                        max_length=24,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "period_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "scope_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("object", "Objekt"),
                            ("accounting", "Buchhaltung"),
                            ("owner", "Eigentümer"),
                            ("tenant", "Mieter"),
                            ("unclear", "unklar"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("reasoning", models.TextField(blank=True, null=True)),
                ("owner_candidates", models.JSONField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, null=True)),
                ("tokens_in", models.PositiveIntegerField(blank=True, null=True)),
                ("tokens_out", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost_eur",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("is_final", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document_classifications",
            },
        ),
        migrations.CreateModel(
            name="DocumentEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_no", models.PositiveIntegerField()),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("person_name", "Personenname"),
                            ("company_name", "Firmenname"),
                            ("unit_label", "Einheit"),
                            ("amount", "Betrag"),
                            ("date", "Datum"),
                            ("period", "Zeitraum"),
                            ("iban", "IBAN"),
                            ("mandate_ref", "Mandatsreferenz"),
                            ("address", "Adresse"),
                            ("object_number", "Objektnummer"),
                            ("id_document_number", "Ausweisnummer"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "value_text",
                    models.CharField(
                        blank=True,
                        help_text="bei iban nur maskierte Form",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "value_normalized",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("iban_last4", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "iban_hash",
                    models.CharField(
                        blank=True,
                        help_text="HMAC-SHA256 hex",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("char_from", models.PositiveIntegerField(blank=True, null=True)),
                ("char_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "match_confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document_entities",
            },
        ),
        migrations.CreateModel(
            name="DocumentOwnerLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "link_kind",
                    models.CharField(
                        choices=[
                            ("whole_document", "gesamtes Dokument"),
                            ("page_range", "Seitenbereich"),
                        ],
                        max_length=16,
                    ),
                ),
                ("page_from", models.PositiveIntegerField(blank=True, null=True)),
                ("page_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "period_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("period_from", models.DateField(blank=True, null=True)),
                ("period_to", models.DateField(blank=True, null=True)),
                ("document_date", models.DateField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "vorgeschlagen"),
                            ("confirmed", "bestätigt"),
                            ("rejected", "abgelehnt"),
                        ],
                        default="suggested",
                        max_length=16,
                    ),
                ),
                (
                    "drive_copy_file_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "document_owner_links",
            },
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_no", models.PositiveIntegerField()),
                (
                    "text_source",
                    models.CharField(
                        choices=[
                            ("text_layer", "Textebene"),
                            ("ocr", "OCR"),
                            ("mixed", "gemischt"),
                            ("empty", "leer"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_scan", models.BooleanField()),
                (
                    "text_content",
                    models.TextField(blank=True, help_text="maskierter Seitentext", null=True),
                ),
                ("text_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("char_count", models.PositiveIntegerField(blank=True, null=True)),
                ("word_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ocr_confidence",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("ocr_engine", models.CharField(blank=True, max_length=40, null=True)),
                ("ocr_language", models.CharField(blank=True, max_length=8, null=True)),
                ("rotation_deg", models.SmallIntegerField(blank=True, null=True)),
                ("masked_entities_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document_pages",
            },
        ),
        migrations.CreateModel(
            name="DocumentSubfolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=2)),
                ("folder_name", models.CharField(max_length=80)),
                ("display_name", models.CharField(max_length=80)),
                ("sort_order", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "document_subfolders",
                "ordering": ["category_id", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTenantLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "link_kind",
                    models.CharField(
                        choices=[
                            ("whole_document", "gesamtes Dokument"),
                            ("page_range", "Seitenbereich"),
                        ],
                        max_length=16,
                    ),
                ),
                ("page_from", models.PositiveIntegerField(blank=True, null=True)),
                ("page_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "period_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("period_from", models.DateField(blank=True, null=True)),
                ("period_to", models.DateField(blank=True, null=True)),
                ("document_date", models.DateField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "vorgeschlagen"),
                            ("confirmed", "bestätigt"),
                            ("rejected", "abgelehnt"),
                        ],
                        default="suggested",
                        max_length=16,
                    ),
                ),
                (
                    "drive_copy_file_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "document_tenant_links",
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("requires_period", models.BooleanField(default=False)),
                ("requires_owner", models.BooleanField(default=False)),
                ("requires_tenant", models.BooleanField(default=False)),
                ("keywords", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "document_types",
                "ordering": ["category_id", "subfolder_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retention_years",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "retention_basis",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("document_date", "Dokumentdatum"),
                            ("period_end", "Ende des Zeitraums"),
                            ("assignment_end", "Ende der Zuordnung"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "retention_policies",
            },
        ),
        migrations.CreateModel(
            name="TrainingSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_from", models.PositiveIntegerField(blank=True, null=True)),
                ("page_to", models.PositiveIntegerField(blank=True, null=True)),
                ("text_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "label_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("object", "Objekt"),
                            ("accounting", "Buchhaltung"),
                            ("owner", "Eigentümer"),
                            ("tenant", "Mieter"),
                            ("unclear", "unklar"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "label_source",
                    models.CharField(
                        choices=[
                            ("review_decision", "Review-Entscheidung"),
                            ("seed", "Startmenge"),
                            ("rules_high_confidence", "Regelwerk mit hoher Konfidenz"),
                            ("manual", "manuell"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=4, default=1, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "training_samples",
            },
        ),
        migrations.CreateModel(
            name="ClassifierModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=40, unique=True)),
                ("algorithm", models.CharField(max_length=48)),
                ("trained_at", models.DateTimeField()),
                ("samples_count", models.PositiveIntegerField()),
                ("metrics", models.JSONField(blank=True, null=True)),
                ("artifact_path", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="activated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "classifier_models",
                "ordering": ["-trained_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        help_text="leer bis Status hashed (Ergänzung Nr. 2)",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("drive_md5", models.CharField(blank=True, max_length=32, null=True)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("mime_type", models.CharField(max_length=120)),
                ("original_name", models.CharField(max_length=255)),
                ("current_name", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("drive_existing", "Drive-Bestand"),
                            ("upload", "Upload"),
                            ("import", "Import"),
                            ("generated", "erzeugt"),
                            ("moved_in", "aus anderem Objekt übernommen"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "drive_file_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("drive_moved_at", models.DateTimeField(blank=True, null=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "origin_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("digital", "digital"),
                            ("scan", "Scan"),
                            ("mixed", "gemischt"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "ocr_cache_key",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "registriert"),
                            ("hashed", "Hash bekannt"),
                            ("ocr_done", "Text erkannt"),
                            ("classified", "klassifiziert"),
                            ("filed", "abgelegt"),
                            ("review", "in Prüfung"),
                            ("duplicate", "Dublette"),
                            ("moved_out", "in anderes Objekt übernommen"),
                            ("error", "Fehler"),
                        ],
                        default="registered",
                        max_length=16,
                    ),
                ),
                ("document_date", models.DateField(blank=True, null=True)),
                (
                    "period_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("period_from", models.DateField(blank=True, null=True)),
                ("period_to", models.DateField(blank=True, null=True)),
                (
                    "final_confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "final_decided_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stage1", "Stufe 1"),
                            ("stage2", "Stufe 2"),
                            ("stage3", "Stufe 3"),
                            ("human", "Mensch"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "classifier_version",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("is_master_with_segments", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField()),
                ("filed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
    ]
