# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai", "0002_fremdschluessel"),
        ("documents", "0001_initial"),
        ("drive", "0001_initial"),
        ("objects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="drive_node",
            field=models.ForeignKey(
                blank=True,
                db_column="drive_node_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="drive.drivenode",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                db_column="duplicate_of_document_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplicates",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="object",
            field=models.ForeignKey(
                db_column="object_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="objects.managedobject",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="target_drive_node",
            field=models.ForeignKey(
                blank=True,
                db_column="target_drive_node_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="drive.drivenode",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope__in", ["object", "owner", "tenant", "misc"])),
                name="ck_categories_scope",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="category_code",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="documents.documentcategory",
            ),
        ),
        migrations.AddField(
            model_name="classificationrule",
            name="target_category",
            field=models.ForeignKey(
                blank=True,
                db_column="target_category_code",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="documents.documentcategory",
            ),
        ),
        migrations.AddField(
            model_name="documentclassification",
            name="ai_call",
            field=models.ForeignKey(
                blank=True,
                db_column="ai_call_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classifications",
                to="ai.aicall",
            ),
        ),
        migrations.AddField(
            model_name="documentclassification",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="category_code",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="documents.documentcategory",
            ),
        ),
        migrations.AddField(
            model_name="documentclassification",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                db_column="decided_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentclassification",
            name="document",
            field=models.ForeignKey(
                db_column="document_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classifications",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="documententity",
            name="document",
            field=models.ForeignKey(
                db_column="document_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entities",
                to="documents.document",
            ),
        ),
    ]
