# Generated by Django 5.2.17 on 2026-09-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_volltextindex_seiten"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classificationrule",
            name="ck_rules_kind",
        ),
        migrations.AddField(
            model_name="classificationrule",
            name="definition",
            field=models.JSONField(
                blank=True,
                help_text="vollständige Regel (scope, when, then, examples) nach E 2.2; Ziele als Codes (B-12)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classificationrule",
            name="version",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Version aus der Regeldatei (E 2.2)"
            ),
        ),
        migrations.AlterField(
            model_name="classificationrule",
            name="rule_kind",
            field=models.CharField(
                choices=[
                    ("filename", "Dateiname"),
                    ("folder", "Herkunftsordner"),
                    ("keyword", "Stichwort im Text"),
                    ("entity", "erkannte Entität"),
                    ("period", "Zeitbezug"),
                    ("composite", "zusammengesetzte Regel (Definition nach E 2.2)"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="classificationrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rule_kind__in",
                        [
                            "filename",
                            "folder",
                            "keyword",
                            "entity",
                            "period",
                            "composite",
                        ],
                    )
                ),
                name="ck_rules_kind",
            ),
        ),
    ]
