# Generated by Django 5.2.17 on 2026-09-12 11:16

import uuid
from django.conf import settings
from django.db import migrations, models


def fill_uuids(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    for row in Document.objects.filter(uuid__isnull=True).only("pk").iterator(chunk_size=500):
        Document.objects.filter(pk=row.pk).update(uuid=uuid.uuid4())


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_regeldefinition_kpi"),
        ("drive", "0003_takeover_sources"),
        ("objects", "0002_eingangsobjekt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="document",
            name="ck_documents_source",
        ),
        # UUID in drei Schritten (Django-Muster fuer eindeutige Felder mit aufrufbarem Standardwert):
        # 1. Feld ohne Eindeutigkeit anlegen, 2. Bestandszeilen einzeln fuellen, 3. eindeutig und Pflicht setzen.
        migrations.AddField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(fill_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="unveränderliche Dokument-UUID für externe Systeme",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="source",
            field=models.CharField(
                choices=[
                    ("drive_existing", "Drive-Bestand"),
                    ("upload", "Upload"),
                    ("import", "Import"),
                    ("generated", "erzeugt"),
                    ("moved_in", "aus anderem Objekt übernommen"),
                    ("paperless", "aus Paperless übernommen"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source__in",
                        [
                            "drive_existing",
                            "upload",
                            "import",
                            "generated",
                            "moved_in",
                            "paperless",
                        ],
                    )
                ),
                name="ck_documents_source",
            ),
        ),
    ]
