# Generated by Django 5.2.17 on 2026-09-12 11:16, ueberarbeitet am 12.09.2026 (Deploy-Lauf 103):
# MariaDB kann Schemaaenderungen nicht zuruecksetzen; bricht diese Migration ab, bleibt die Datenbank halb
# migriert. Alle Schemaschritte pruefen deshalb den Ist-Zustand und lassen sich gefahrlos wiederholen.
# Ausserdem darf das UUID-Feld nicht mit aufrufbarem Standardwert angelegt werden: Django berechnet den Wert
# einmal fuer die ganze Tabelle, alle Bestandszeilen erhielten dieselbe UUID und der Unique-Index scheiterte.

import uuid

from django.conf import settings
from django.db import migrations, models

TABLE = "documents"
CONSTRAINT = "ck_documents_source"
OLD_SOURCES = ["drive_existing", "upload", "import", "generated", "moved_in"]
NEW_SOURCES = [*OLD_SOURCES, "paperless"]


def _columns(schema_editor) -> set[str]:
    with schema_editor.connection.cursor() as cursor:
        return {c.name for c in schema_editor.connection.introspection.get_table_description(cursor, TABLE)}


def _constraints(schema_editor) -> dict:
    with schema_editor.connection.cursor() as cursor:
        return schema_editor.connection.introspection.get_constraints(cursor, TABLE)


def _old_constraint() -> models.CheckConstraint:
    return models.CheckConstraint(condition=models.Q(("source__in", OLD_SOURCES)), name=CONSTRAINT)


def drop_source_constraint(apps, schema_editor):
    if CONSTRAINT in _constraints(schema_editor):
        Document = apps.get_model("documents", "Document")
        schema_editor.remove_constraint(Document, _old_constraint())


def restore_source_constraint(apps, schema_editor):
    if CONSTRAINT not in _constraints(schema_editor):
        Document = apps.get_model("documents", "Document")
        schema_editor.add_constraint(Document, _old_constraint())


def add_uuid_column(apps, schema_editor):
    """Spalte ohne Standardwert anlegen (NULL erlaubt); die Werte setzt fill_uuids je Zeile."""
    if "uuid" in _columns(schema_editor):
        return
    Document = apps.get_model("documents", "Document")
    field = models.UUIDField(null=True, editable=False)
    field.set_attributes_from_name("uuid")
    schema_editor.add_field(Document, field)


def remove_uuid_column(apps, schema_editor):
    """Rueckwaerts: Spalte entfernen, falls vorhanden. Der uebergebene Modellzustand kennt das Feld hier nicht
    (SeparateDatabaseAndState), deshalb wird das Feldobjekt wie beim Anlegen selbst gebaut."""
    if "uuid" not in _columns(schema_editor):
        return
    Document = apps.get_model("documents", "Document")
    field = models.UUIDField(null=True, editable=False)
    field.set_attributes_from_name("uuid")
    schema_editor.remove_field(Document, field)


def fill_uuids(apps, schema_editor):
    """Jede Bestandszeile erhaelt eine eigene UUID. Alle Zeilen werden neu gesetzt, weil ein frueherer Lauf
    denselben Wert in jede Zeile geschrieben haben kann; eine externe Verknuepfung ueber die UUID gibt es vor
    dieser Migration nicht."""
    Document = apps.get_model("documents", "Document")
    for pk in Document.objects.order_by("pk").values_list("pk", flat=True).iterator(chunk_size=1000):
        Document.objects.filter(pk=pk).update(uuid=uuid.uuid4())


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_regeldefinition_kpi"),
        ("drive", "0003_takeover_sources"),
        ("objects", "0002_eingangsobjekt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(model_name="document", name=CONSTRAINT),
            ],
            database_operations=[
                migrations.RunPython(drop_source_constraint, restore_source_constraint),
            ],
        ),
        # UUID in drei Schritten (Django-Muster fuer eindeutige Felder mit aufrufbarem Standardwert):
        # 1. Feld ohne Eindeutigkeit anlegen, 2. Bestandszeilen einzeln fuellen, 3. eindeutig und Pflicht setzen.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="document",
                    name="uuid",
                    field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_uuid_column, remove_uuid_column),
            ],
        ),
        migrations.RunPython(fill_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="unveränderliche Dokument-UUID für externe Systeme",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="source",
            field=models.CharField(
                choices=[
                    ("drive_existing", "Drive-Bestand"),
                    ("upload", "Upload"),
                    ("import", "Import"),
                    ("generated", "erzeugt"),
                    ("moved_in", "aus anderem Objekt übernommen"),
                    ("paperless", "aus Paperless übernommen"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", NEW_SOURCES)),
                name=CONSTRAINT,
            ),
        ),
    ]
