# Generated by Django 5.2.17 on 2026-09-10 13:59

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=24, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "permissions",
                    models.JSONField(
                        default=list, help_text="Liste von Berechtigungsschluesseln"
                    ),
                ),
                ("is_system", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "roles",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("display_name", models.CharField(max_length=120)),
                (
                    "password",
                    models.CharField(
                        blank=True, db_column="password_hash", max_length=255, null=True
                    ),
                ),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "google_subject",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "eingeladen"),
                            ("active", "aktiv"),
                            ("disabled", "gesperrt"),
                        ],
                        default="invited",
                        max_length=16,
                    ),
                ),
                ("failed_login_count", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, db_column="last_login_at", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delete_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "active_key",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                deleted_at__isnull=True, then=models.F("email")
                            ),
                            default=models.Value(None),
                        ),
                        output_field=models.EmailField(max_length=254, null=True),
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "indexes": [models.Index(fields=["role"], name="ix_users_role")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("active_key",), name="uq_users_email_active"
                    )
                ],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
