# Generated by Django 5.2.17 on 2026-09-12 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0006_dokument_uuid_quelle_paperless"),
        ("objects", "0002_eingangsobjekt"),
        ("review", "0002_fallarten_zuordnung_konflikt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_no", models.PositiveSmallIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("paperless", "Paperless-ngx"),
                            ("drive", "Google Drive"),
                            ("app", "Anwendung"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_external_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("label", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_versions",
            },
        ),
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("paperless", "Paperless-ngx"),
                            ("drive", "Google Drive"),
                            ("app", "Anwendung"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("archive", "OCR-Archivfassung"),
                            ("snapshot", "Exportfassung (Snapshot)"),
                            ("index_stub", "Indexbeleg"),
                        ],
                        default="original",
                        max_length=16,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                (
                    "external_version",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "parent_external_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "checksum_md5",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("mime_type", models.CharField(blank=True, max_length=120, null=True)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("remote_modified_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("synced_fields", models.JSONField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "vorgemerkt"),
                            ("linked", "verknüpft"),
                            ("synced", "abgeglichen"),
                            ("changed_remote", "extern geändert"),
                            ("conflict", "Konflikt"),
                            ("missing", "extern nicht gefunden"),
                            ("trashed", "im Papierkorb"),
                            ("no_access", "kein Zugriff"),
                            ("tombstone", "Löschung bestätigt"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "state_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tombstone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_links",
                        to="documents.document",
                    ),
                ),
                (
                    "tombstone_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="tombstone_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        db_column="version_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="links",
                        to="sync.documentversion",
                    ),
                ),
            ],
            options={
                "db_table": "sync_links",
            },
        ),
        migrations.CreateModel(
            name="InventoryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("paperless", "Paperless-ngx"),
                            ("drive", "Google Drive"),
                            ("app", "Anwendung"),
                        ],
                        max_length=16,
                    ),
                ),
                ("dry_run", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "geplant"),
                            ("running", "läuft"),
                            ("paused", "pausiert"),
                            ("done", "abgeschlossen"),
                            ("failed", "fehlgeschlagen"),
                            ("aborted", "abgebrochen"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("scope", models.JSONField(blank=True, null=True)),
                ("cursor_before", models.JSONField(blank=True, null=True)),
                ("page_state", models.JSONField(blank=True, null=True)),
                ("counters", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="started_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sync_inventory_runs",
            },
        ),
        migrations.CreateModel(
            name="SyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("paperless", "Paperless-ngx"),
                            ("drive", "Google Drive"),
                            ("app", "Anwendung"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=48)),
                ("value", models.TextField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "sync_cursors",
                "constraints": [
                    models.UniqueConstraint(fields=("system", "name"), name="uq_sync_cursors_name"),
                    models.CheckConstraint(
                        condition=models.Q(("system__in", ["paperless", "drive", "app"])),
                        name="ck_sync_cursors_system",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("op_key", models.CharField(max_length=200, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("paperless_push", "Datei nach Paperless übertragen"),
                            ("paperless_await_task", "Paperless-Aufgabe verfolgen"),
                            (
                                "paperless_push_meta",
                                "Metadaten nach Paperless schreiben",
                            ),
                            ("paperless_pull", "Dokument aus Paperless übernehmen"),
                            ("paperless_pull_meta", "Metadaten aus Paperless lesen"),
                            ("paperless_index_stub", "Indexbeleg in Paperless anlegen"),
                            ("drive_set_props", "Drive-Kennzeichen setzen"),
                            ("drive_export_snapshot", "Google-Dokument exportieren"),
                            ("drive_register", "Drive-Datei registrieren"),
                            ("assign_object", "Objekt zuordnen"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("paperless", "Paperless-ngx"),
                            ("drive", "Google Drive"),
                            ("app", "Anwendung"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paperless", "Paperless-ngx"),
                            ("drive", "Google Drive"),
                            ("app", "Anwendung"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "source_revision",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("desired_state", models.JSONField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "wartet"),
                            ("running", "läuft"),
                            ("done", "fertig"),
                            ("failed", "fehlgeschlagen"),
                            ("blocked", "blockiert"),
                            ("cancelled", "verworfen"),
                            ("skipped", "übersprungen"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=100)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=80, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "blocked_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_operations",
                        to="documents.document",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        db_column="link_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations",
                        to="sync.externallink",
                    ),
                ),
            ],
            options={
                "db_table": "sync_operations",
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("paperless", "Paperless-ngx"),
                            ("drive", "Google Drive"),
                            ("app", "Anwendung"),
                        ],
                        max_length=16,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                (
                    "parent_external_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=120, null=True)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "checksum_md5",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("remote_modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("pending", "offen"),
                            ("link_existing", "vorhandenes Dokument verknüpft"),
                            ("import_new", "neu übernommen"),
                            ("duplicate", "Dublette verknüpft"),
                            ("export_snapshot", "Exportfassung"),
                            ("index_stub", "Indexbeleg"),
                            ("unsupported", "nicht übertragbar"),
                            ("out_of_scope", "außerhalb des Umfangs"),
                            ("in_progress", "in Verarbeitung"),
                            ("error", "Fehler"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "target_external_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        blank=True,
                        db_column="object_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        db_column="run_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sync.inventoryrun",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        db_column="operation_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sync.syncoperation",
                    ),
                ),
            ],
            options={
                "db_table": "sync_inventory_items",
            },
        ),
        migrations.CreateModel(
            name="AssignmentExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("confirm", "Vorschlag bestätigt"),
                            ("correct", "Vorschlag korrigiert"),
                            ("reject", "Vorschlag verworfen"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("human", "manuelle Bestätigung"),
                            ("auto_verified", "automatisch, später bestätigt"),
                            ("import_unverified", "Altbestand, ungeprüft"),
                        ],
                        default="human",
                        max_length=24,
                    ),
                ),
                ("decided_at", models.DateTimeField()),
                ("features", models.JSONField(blank=True, null=True)),
                ("evidence", models.JSONField(blank=True, null=True)),
                (
                    "rule_version",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="decided_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_examples",
                        to="documents.document",
                    ),
                ),
                (
                    "previous_object",
                    models.ForeignKey(
                        blank=True,
                        db_column="previous_object_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "proposed_object",
                    models.ForeignKey(
                        blank=True,
                        db_column="proposed_object_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "review_case",
                    models.ForeignKey(
                        blank=True,
                        db_column="review_case_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="review.reviewcase",
                    ),
                ),
                (
                    "target_object",
                    models.ForeignKey(
                        blank=True,
                        db_column="target_object_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="objects.managedobject",
                    ),
                ),
            ],
            options={
                "db_table": "sync_assignment_examples",
                "indexes": [models.Index(fields=["target_object", "kind"], name="ix_sync_examples_target")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["confirm", "correct", "reject"])),
                        name="ck_sync_examples_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "source__in",
                                ["human", "auto_verified", "import_unverified"],
                            )
                        ),
                        name="ck_sync_examples_source",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssignmentRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("kind", models.CharField(default="feature_combo", max_length=32)),
                ("conditions", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_from", models.JSONField(blank=True, null=True)),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("last_hit_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deactivated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_rules",
                        to="objects.managedobject",
                    ),
                ),
            ],
            options={
                "db_table": "sync_assignment_rules",
                "indexes": [models.Index(fields=["is_active", "kind"], name="ix_sync_rules_active")],
                "constraints": [
                    models.UniqueConstraint(fields=("code", "version"), name="uq_sync_rules_version")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(fields=("document", "version_no"), name="uq_doc_versions_no"),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(fields=("document", "sha256"), name="uq_doc_versions_hash"),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_system__in", ["paperless", "drive", "app"])),
                name="ck_doc_versions_source",
            ),
        ),
        migrations.AddIndex(
            model_name="externallink",
            index=models.Index(fields=["system", "state"], name="ix_sync_links_state"),
        ),
        migrations.AddIndex(
            model_name="externallink",
            index=models.Index(fields=["checksum_sha256"], name="ix_sync_links_sha"),
        ),
        migrations.AddConstraint(
            model_name="externallink",
            constraint=models.UniqueConstraint(
                fields=("system", "external_id", "role"), name="uq_sync_links_external"
            ),
        ),
        migrations.AddConstraint(
            model_name="externallink",
            constraint=models.UniqueConstraint(
                fields=("document", "system", "role"), name="uq_sync_links_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="externallink",
            constraint=models.CheckConstraint(
                condition=models.Q(("system__in", ["paperless", "drive", "app"])),
                name="ck_sync_links_system",
            ),
        ),
        migrations.AddConstraint(
            model_name="externallink",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["original", "archive", "snapshot", "index_stub"])),
                name="ck_sync_links_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="externallink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "pending",
                            "linked",
                            "synced",
                            "changed_remote",
                            "conflict",
                            "missing",
                            "trashed",
                            "no_access",
                            "tombstone",
                        ],
                    )
                ),
                name="ck_sync_links_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["planned", "running", "paused", "done", "failed", "aborted"],
                    )
                ),
                name="ck_sync_inv_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["paperless", "drive", "app"])),
                name="ck_sync_inv_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="syncoperation",
            index=models.Index(fields=["status", "next_attempt_at"], name="ix_sync_ops_due"),
        ),
        migrations.AddIndex(
            model_name="syncoperation",
            index=models.Index(fields=["document", "kind"], name="ix_sync_ops_document"),
        ),
        migrations.AddConstraint(
            model_name="syncoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "paperless_push",
                            "paperless_await_task",
                            "paperless_push_meta",
                            "paperless_pull",
                            "paperless_pull_meta",
                            "paperless_index_stub",
                            "drive_set_props",
                            "drive_export_snapshot",
                            "drive_register",
                            "assign_object",
                        ],
                    )
                ),
                name="ck_sync_ops_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "running",
                            "done",
                            "failed",
                            "blocked",
                            "cancelled",
                            "skipped",
                        ],
                    )
                ),
                name="ck_sync_ops_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("system__in", ["paperless", "drive", "app"])),
                name="ck_sync_ops_system",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["run", "disposition"], name="ix_sync_inv_items_disp"),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                fields=("run", "system", "external_id"), name="uq_sync_inv_items"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "disposition__in",
                        [
                            "pending",
                            "link_existing",
                            "import_new",
                            "duplicate",
                            "export_snapshot",
                            "index_stub",
                            "unsupported",
                            "out_of_scope",
                            "in_progress",
                            "error",
                        ],
                    )
                ),
                name="ck_sync_inv_disp",
            ),
        ),
    ]
