# Generated by Django 5.2.17 on 2026-09-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai", "0002_fremdschluessel"),
        ("documents", "0002_fremdschluessel_ai_drive_objects"),
        ("objects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_kind",
                    models.CharField(
                        choices=[
                            ("owner_list", "Eigentümerliste"),
                            ("tenant_list", "Mieterliste"),
                            ("mixed", "gemischt"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_format",
                    models.CharField(
                        choices=[
                            ("pdf_scan", "PDF (Scan)"),
                            ("pdf_digital", "PDF (digital)"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                            ("immoware24", "Immoware24-Export"),
                            ("domus", "Domus-Export"),
                            ("other", "sonstige"),
                        ],
                        max_length=24,
                    ),
                ),
                ("parser_profile", models.CharField(max_length=48)),
                ("parser_version", models.CharField(max_length=24)),
                ("source_sha256", models.CharField(max_length=64)),
                ("source_file_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "hochgeladen"),
                            ("parsed", "eingelesen"),
                            ("in_review", "in Prüfung"),
                            ("committed", "übernommen"),
                            ("partially_committed", "teilweise übernommen"),
                            ("rejected", "abgelehnt"),
                            ("failed", "fehlgeschlagen"),
                        ],
                        default="uploaded",
                        max_length=24,
                    ),
                ),
                ("rows_total", models.PositiveIntegerField(blank=True, null=True)),
                ("rows_uncertain", models.PositiveIntegerField(blank=True, null=True)),
                ("rows_confirmed", models.PositiveIntegerField(blank=True, null=True)),
                ("rows_rejected", models.PositiveIntegerField(blank=True, null=True)),
                ("rows_committed", models.PositiveIntegerField(blank=True, null=True)),
                ("column_mapping", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_call",
                    models.ForeignKey(
                        blank=True,
                        db_column="ai_call_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ai.aicall",
                    ),
                ),
                (
                    "committed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="committed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        db_column="object_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="objects.managedobject",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="uploaded_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "import_batches",
            },
        ),
        migrations.CreateModel(
            name="ImportColumnProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "source_format",
                    models.CharField(
                        choices=[
                            ("pdf_scan", "PDF (Scan)"),
                            ("pdf_digital", "PDF (digital)"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                            ("immoware24", "Immoware24-Export"),
                            ("domus", "Domus-Export"),
                            ("other", "sonstige"),
                        ],
                        max_length=24,
                    ),
                ),
                ("parser_profile", models.CharField(max_length=48)),
                ("column_mapping", models.JSONField()),
                (
                    "previous_manager_name",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "import_column_profiles",
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_no", models.PositiveIntegerField()),
                ("sub_index", models.PositiveSmallIntegerField(default=0)),
                ("page_no", models.PositiveIntegerField(blank=True, null=True)),
                ("raw_data", models.JSONField()),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("parsed_fields", models.JSONField()),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("parsed", "eingelesen"),
                            ("uncertain", "unsicher"),
                            ("confirmed", "bestätigt"),
                            ("rejected", "abgelehnt"),
                            ("committed", "übernommen"),
                            ("duplicate", "Dublette"),
                        ],
                        default="parsed",
                        max_length=16,
                    ),
                ),
                (
                    "target_entity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("owner", "Eigentümer"),
                            ("unit", "Einheit"),
                            ("owner_unit_assignment", "Eigentümerzuordnung"),
                            ("tenant", "Mieter"),
                            ("lease", "Mietverhältnis"),
                            ("tenant_unit_assignment", "Mieterzuordnung"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("committed_targets", models.JSONField(blank=True, null=True)),
                ("uncertainty_reasons", models.JSONField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        db_column="batch_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="imports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "import_rows",
            },
        ),
    ]
