# Generated by Django 5.2.17 on 2026-09-10 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField(null=True)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("list", "List"),
                            ("object", "Object"),
                        ],
                        max_length=16,
                    ),
                ),
                ("category", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=500)),
                ("validation", models.JSONField(blank=True, null=True)),
                ("is_secret", models.BooleanField(default=False)),
                ("is_deprecated", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_settings",
                "ordering": ["category", "key"],
                "indexes": [
                    models.Index(fields=["category"], name="ix_settings_category")
                ],
            },
        ),
    ]
